language: python

python:
  - 3.8

install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - pip install coveralls

script:
  - coverage run -m unittest

after_success:
  - coveralls
